### ISSUE TITLE
Unnecessary strict dependency?

### ISSUE THREAD

**Issue by JonathanStoye** [pke/eslint-plugin-redux-saga#29]
Is it necessary to strictly bind to eslint version `3.19.0`? Would be nice to get rid of that in favour of a more generic version as suggested in the [npm docs](https://eslint.org/docs/developer-guide/shareable-configs). This way the following warning could be prevented:

`npm WARN eslint-plugin-redux-saga@0.4.0 requires a peer of eslint@^3.19.0 but none was installed.`

https://github.com/pke/eslint-plugin-redux-saga/blob/41c49c3588dee3816cba14e3e18eeb4511025c75/package.json#L33

**Comment by piuccio** [comment]
The latest package.json requires `4.1.0` but it's never been published to npm. Would be great at least to have a new release

**Comment by pke** [comment]
My bad. Will publish the version. You can create a pr for the peer dependency

**Comment by pke** [comment]
Released as 0.5.0 now. Thanks @JonathanStoye for #30
