### ISSUE TITLE
Publish package

### ISSUE THREAD

**Issue by mxstbr** [pke/eslint-plugin-redux-saga#3]
Can't find it under `eslint-plugin-redux-saga` on `npm`, am I missing something?

**Comment by pke** [comment]
I think that's because it was never published ;)

**Comment by mxstbr** [comment]
Damn 😢 Would love to see this finished/published!

**Comment by pke** [comment]
I am sorry to see you sad. I only now saw anybody actually tried to use this already. Had my notifications not set up properly for this repo.
I'll see what I can do to update this (it was merely an online backup of my efforts so far).

**Comment by pke** [comment]
Your wish has been granted: https://www.npmjs.com/package/eslint-plugin-redux-saga
