### ISSUE TITLE
no-unhandled-error expects try-catch around effects that can't be caught

### ISSUE THREAD

**Issue by ycai2** [pke/eslint-plugin-redux-saga#40]
Saga [doc](https://redux-saga.js.org/docs/advanced/ForkModel.html), in the Error Propagation section, points out **"you can't catch errors from forked tasks"**. 
Using the no-unhandled-error rule, I still need to put effects such as `fork` and `takeEvery` (which is also forked) in catch blocks, even though they don't do anything. This also means I can never achieve code-coverage on those catch blocks.
Maybe there could be exception for specific effects.

**Comment by pke** [comment]
Thank you for reporting. I currently have limited time avail to work on this lib but I'll see what I can do. Maybe you want to try to create a PR yourself?

**Comment by ycai2** [comment]
@pke No, I tried 0.7.0 but it doesn't fixes this.

**Comment by pke** [comment]
@ycai2 Can you please post your code snipped?

**Comment by pke** [comment]
@ycai2 Ok I think I have tackled this now with 0.8.0. Could you please verify?

**Comment by ycai2** [comment]
Looks like it's fixed. Thanks a lot! You can close this.
