### ISSUE TITLE
no-yield-in-race handle arrays

### ISSUE THREAD

**Issue by f3ist** [pke/eslint-plugin-redux-saga#44]
When passing an array of effects as show in the [API](https://redux-saga.js.org/docs/api/#raceeffects-with-array), `no-yield-in-race` doesn't properly handle it and errors with: `race must have on object hash as the only argument`

**Comment by pke** [comment]
That should be easy to fix tonight ;)

**Comment by pke** [comment]
Published as [![npm version](https://img.shields.io/npm/v/eslint-plugin-redux-saga.svg?style=flat-square)](https://badge.fury.io/js/eslint-plugin-redux-saga)
