### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by salzhrani** [pke/eslint-plugin-redux-saga#5]
I am facing an issue with `eslint@3.1.1` and vs code. I get this error
`Failed to plugin redux-saga: Cannot find module 'eslint-plugin-redux-saga'`. Although it is installed.

**Comment by cristian-sima** [comment]
@pke Same here for `eslint@3.3.1`

**Comment by pke** [comment]
No idea what is going on there. The `peer-dependencies` look good.

**Comment by salzhrani** [comment]
Not sure if it is related to the lack of `main` in `package.json` or missing `index.js`

**Comment by pke** [comment]
It shouldn't. I'll have to test it later.

**Comment by pke** [comment]
This seemed to have been a glitch in `npm`. It works now. Can you verify?

**Comment by cristian-sima** [comment]
Same problem

![image](https://cloud.githubusercontent.com/assets/12199042/17923308/41f50b5c-69ec-11e6-878c-630e1d3310ab.png)

What makes me curios is that there are no releases on Github repository

**Comment by pke** [comment]
Try to delete your npm cache.

```
npm verb etag https://registry.npmjs.org/fsevents from cache
npm verb get saving fsevents to C:\Users\Philipp\AppData\Roaming\npm-cache\registry.npmjs.org\fsevents\.cache.json
npm verb correctMkdir C:\Users\Philipp\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
npm verb correctMkdir C:\Users\Philipp\AppData\Roaming\npm-cache\_locks correctMkdir not in flight; initializing
npm verb lock using C:\Users\Philipp\AppData\Roaming\npm-cache\_locks\staging-b3671b77821e181c.lock for C:\dev\projects\evopark\app\node_modules\.staging
npm verb unbuild node_modules\.staging\eslint-plugin-redux-saga-c0d02b56
npm verb gentlyRm don't care about contents; nuking C:\dev\projects\evopark\app\node_modules\.staging\eslint-plugin-redux-saga-c0d02b56
npm verb tar unpack C:\Users\Philipp\AppData\Roaming\npm-cache\eslint-plugin-redux-saga\0.1.1\package.tgz
npm verb tar unpacking to C:\dev\projects\evopark\app\node_modules\.staging\eslint-plugin-redux-saga-c0d02b56
npm verb gentlyRm don't care about contents; nuking C:\dev\projects\evopark\app\node_modules\.staging\eslint-plugin-redux-saga-c0d02b56
npm verb gentlyRm don't care about contents; nuking C:\dev\projects\evopark\app\node_modules\.staging\eslint-plugin-redux-saga-c0d02b56\node_modules
npm info lifecycle eslint-plugin-redux-saga@0.1.1~preinstall: eslint-plugin-redux-saga@0.1.1
npm info linkStuff eslint-plugin-redux-saga@0.1.1
npm verb linkBins eslint-plugin-redux-saga@0.1.1
npm verb linkMans eslint-plugin-redux-saga@0.1.1
npm info lifecycle eslint-plugin-redux-saga@0.1.1~install: eslint-plugin-redux-saga@0.1.1
npm info lifecycle eslint-plugin-redux-saga@0.1.1~postinstall: eslint-plugin-redux-saga@0.1.1
npm verb unlock done using C:\Users\Philipp\AppData\Roaming\npm-cache\_locks\staging-b3671b77821e181c.lock for C:\dev\projects\evopark\app\node_modules\.staging
evopark@2.3.6 C:\dev\projects\evopark\app
+-- eslint-plugin-redux-saga@0.1.1  extraneous
`-- UNMET PEER DEPENDENCY redux-saga@0.11.0

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN eslint-plugin-redux-saga@0.1.1 requires a peer of redux-saga@^0.9.5 but none was installed.
npm verb exit [ 0, true ]
npm info ok

```

**Comment by cristian-sima** [comment]
Did it. Same...

![image](https://cloud.githubusercontent.com/assets/12199042/17923622/a8eda246-69ed-11e6-9d66-250172aa1ef5.png)

**Comment by pke** [comment]
As you could see. I can install it. So it seems to be a problem with your version of `npm3`.
I can't risk to update my npm/node now though.

**Comment by cristian-sima** [comment]
It is the only package with creates problems (I have installed ... let me count ... 73 packages (without this)

**Comment by cristian-sima** [comment]
It is something to do with `eslint-plugin-redux-saga`. I tried to install now other package and it worked: 

![image](https://cloud.githubusercontent.com/assets/12199042/17924411/3753be3c-69f1-11e6-8f53-67e63a9286cd.png)

**Comment by pdf** [comment]
@pke the following:
```
npm ERR! fetch failed https://registry.npmjs.org/eslint-plugin-redux-saga/-/eslint-plugin-redux-saga-0.1.1.tgz
```
strongly suggests that the package cannot be found on npm, can you please try re-uploading it?  Are you sure your successful install didn't come from cache?

**Comment by pke** [comment]
npm staff is investigating this since two weeks now

**Comment by pke** [comment]
Updated to 0.1.2
Please all try again.

**Comment by jstockwin** [comment]
@pke There seem to be two issues under discussion here. I was having problems downloading `0.1.1` from npm, and that is now fixed - `0.1.2` downloads properly. 

However, the initial reported issue was `Failed to plugin redux-saga: Cannot find module 'eslint-plugin-redux-saga'` after installation, and I still get this error.

**Comment by pke** [comment]
Seems like I totally forgot to export the rules.
I fixed that in https://github.com/pke/eslint-plugin-redux-saga/tree/v0.1.3
Tested it with a fresh folder.
Does it work for you guys now?

**Comment by jstockwin** [comment]
Works for me 👍

**Comment by pke** [comment]
@salzhrani @cristian-sima working for you both too now then I can close this one?

**Comment by cristian-sima** [comment]
Afirmative

**Comment by pke** [comment]
Great to hear. Sorry @all for the delay. Was my first eslint plugin and first npm package being published.

**Comment by salzhrani** [comment]
Greatly appreciated.

**Comment by jstockwin** [comment]
No worries - thanks for the quick fix!

**Comment by the1mills** [comment]
@pke when publishing NPM packages, this tool can prevent the original problem that occurred https://github.com/ORESoftware/r2g

**Comment by DaveNguyenHuy** [comment]
same issue and have no idea :(

**Comment by pke** [comment]
This has been fixed, hasn't it? What exactly is your issue @DaveNguyenHuy?
