### ISSUE TITLE
Peer dependency warning

### ISSUE THREAD

**Issue by ahce** [pke/eslint-plugin-redux-saga#53]
## Expected behavior
No peer warn

## Actual behavior
npm WARN eslint-plugin-redux-saga@0.10.0 requires a peer of redux-saga@>= 0.11.1 < 1 || 1.0.0-beta.3 but none is installed. You must install peer dependencies yourself.

## Steps to reproduce
- npm install --save redux-saga@1.0.0
 
## Environment

| Tech                | Version |
|---------------------|---------|
| redux-saga | 1.0.0 |
| eslint-plugin-redux-saga | 0.10.0 |

**Comment by pke** [comment]
Yes the peer-dependency is too strict. A patch should be easy to set the version to a less restrictive one. I'll do that later.

**Comment by ahce** [comment]
@pke please, remember this

**Comment by pke** [comment]
Closed by #54 Thanks to @amercier

**Comment by pke** [comment]
And relased as 1.0.0 (to match redux-saga ;)
