### ISSUE TITLE
404 page

### ISSUE THREAD

**Issue by cristian-sima** [pke/eslint-plugin-redux-saga#6]
I go on https://www.npmjs.com/package/eslint-plugin-redux-saga and click on no-yield-in-race and I got 404

![image](https://cloud.githubusercontent.com/assets/12199042/17887258/4c0d86b4-692e-11e6-9b11-68aff0cdfa8c.png)

**Comment by pke** [comment]
Thanks for reporting.
This was fixed already in #4ecad894 but never published. Made a patch release `0.1.1`

**Comment by cristian-sima** [comment]
@pke Thanks for your quick response. Can you have a look also here ? https://github.com/pke/eslint-plugin-redux-saga/issues/5
