### ISSUE TITLE
Can't install the 0.1.1 version

### ISSUE THREAD

**Issue by cristian-sima** [pke/eslint-plugin-redux-saga#7]
I do not have any problem with Internet connection

![image](https://cloud.githubusercontent.com/assets/12199042/17896336/f7aca37c-6958-11e6-89c3-f29b6f156fdc.png)

**Comment by pke** [comment]
No idea. Also can't `npm i` it. same 404 error.

**Comment by pke** [comment]
This seemed to have been a glitch in `npm`. It works now. Can you verify?

**Comment by cristian-sima** [comment]
I responded here https://github.com/pke/eslint-plugin-redux-saga/issues/5#issuecomment-241992890
