### ISSUE TITLE
yield-effects autofix modifies code functionality violating eslint best practices

### ISSUE THREAD

**Issue by wdoug** [pke/eslint-plugin-redux-saga#71]
I just tried to add this plugin to our codebase and noticed that if with code like this:
```js
const requests = endpoints.map(endpoint => call(fetch, endpoint));
yield all(requests);
```
The autofix for the `yield-effects` rule will update code to be:
```js
const requests = endpoints.map(endpoint => yield call(fetch, endpoint));
yield all(requests);
```

There are two less than ideal things here, so I'll open a second issue for the second request, but the first is that the runtime functionality of the code is changed. The [eslint best practices for applying fixes](https://eslint.org/docs/developer-guide/working-with-rules#applying-fixes-1) say this:
> Avoid any fixes that could change the runtime behavior of code and cause it to stop working

As of [eslint 6.7](https://eslint.org/blog/2019/11/eslint-v6.7.0-released#suggestions-api) (released Nov 2019), there is a new [suggestions API](https://eslint.org/docs/developer-guide/working-with-rules#providing-suggestions) that allows editors to provide an optional ability for users to apply fixes that could change the underlying code functionality.

**Comment by pke** [comment]
Nice catch, @wdoug.
There are always edge-cases and as you mentioned in your other filed issues, infinite ones for this one.
Thanks for helping this plugin to become more robust.
Good idea to use the new suggestion API which I was unaware of until you mentioned it.
