### ISSUE TITLE
yield-effects rule triggers when it shouldn't

### ISSUE THREAD

**Issue by jstockwin** [pke/eslint-plugin-redux-saga#8]
I've just tried implementing this in react-boilerplate, however, the `yield-effects` rule is triggering on [this line](https://github.com/mxstbr/react-boilerplate/blob/master/app/store.js#L11), which seems like a bug to me?

**Comment by pke** [comment]
Fixed by 39f2e7a44707fa12ab7e33b19939900785608b2b
