### ISSUE TITLE
Update deps version: redux-saga

### ISSUE THREAD

**Issue by nktssh** [pke/eslint-plugin-redux-saga#9]
eslint-plugin-redux-saga@0.1.4 requires a peer of redux-saga@^0.11.1

Latest redux-saga version is 0.12

**Comment by pke** [comment]
What would be a good semver constraint for the peer dependency? What you guys think?

**Comment by epikhighs** [comment]
I'm getting this error as well. Not sure why NPM is complaining b/c I thought the caret should mean minor releases are fine.

**Comment by epikhighs** [comment]
maybe you should try 0.x instead of the caret

https://nodejs.org/en/blog/npm/peer-dependencies/#using-peer-dependencies

**Comment by pke** [comment]
would you mind creating a PR? I am totally busy atm.

**Comment by epikhighs** [comment]
@pke  https://github.com/pke/eslint-plugin-redux-saga/pull/10

**Comment by pke** [comment]
Closed by #10
